import { createRoot } from 'react-dom/client';
import { MemoryRouter } from 'react-router-dom';
import { Routing } from '../../src/pages/Routing';
import RoutingModules from '../../src/pages/RoutingModules';
import { Applications } from '../../src/pages/Applications';
import { Connections } from '../../src/pages/Connections';
import { TunnelLogs } from '../../src/pages/TunnelLogs';
import { CrossPlatformSync } from '../../src/pages/CrossPlatformSync';
import { MihomoProfiles } from '../../src/pages/MihomoProfiles';
import { api, defaultAppPreferences, type RoutingProfile, type CrossSyncSession } from '../../src/lib/api';
import { useAppStore } from '../../src/store';
import { useCoreStore } from '../../src/coreStore';
import '../../src/styles.css';
import '../../src/universal.css';
import '../../src/secondary.css';
import '../../src/preview-parity.css';
import '../../src/desktop-shell.css';

const params=new URLSearchParams(location.search),mode=params.get('mode')??'routing';
const style=params.get('style')==='material_you'?'material_you':params.get('style')==='dotted'?'dotted':'signal';
document.body.dataset.uiStyle=style;document.body.dataset.theme=params.get('theme')??'dark';
if(params.has('native'))(window as unknown as {__TAURI_INTERNALS__:unknown}).__TAURI_INTERNALS__={invoke:async()=>{throw Error('Unexpected audit IPC');}};
const calls:string[]=[];(window as unknown as {auditCalls:string[]}).auditCalls=calls;
const profile:RoutingProfile={id:'fixture',name:'Тестовый маршрут с длинным названием',description:'Описание',builtin:false,domain_strategy:'AsIs',rule_order:'block-direct-proxy',global_proxy:false,bypass_local_ip:true,fake_dns:false,remote_dns_ip:'1.1.1.1',local_dns_ip:'system',remote_dns_url:'https://dns.invalid/dns-query',direct_domains:[],direct_ips:[],proxy_domains:[],proxy_ips:[],block_domains:[],block_ips:[],source_url:null,update_interval_hours:0,last_updated_at:null};
const sync:CrossSyncSession={state:'idle',devices:[],qr_payload:null,comparison_code:null,expires_at_ms:null,remote_device:null,remote_inventory:null,remote_device_info:null,remote_subscriptions:[],pending_direction:null,pending_categories:null,result:null,error:null,server_port:null};
async function read<T>(name:string,value:T):Promise<T>{calls.push(name);await new Promise(r=>setTimeout(r,10));if(params.has('fail'))throw Error('Контролируемая ошибка загрузки');return value;}
api.listRoutingProfiles=()=>read('routing-list',{active:'fixture',profiles:params.has('populated')?[{id:profile.id,name:profile.name+' с очень длинным текстом'.repeat(7),description:profile.description,builtin:false,rules_count:0,action:'proxy',strategy:'rule'}]:[]});
api.getRoutingProfile=()=>read('routing-profile',profile);
api.listRoutingModules=()=>read('modules',params.has('populated')?[{id:'fixture',name:'Очень длинный модуль '+('название '.repeat(12)),enabled:true,text:'[Rule]\nDOMAIN-SUFFIX,example.invalid,PROXY'}]:[]);
api.listInstalledApps=()=>read('apps',params.has('populated')?[{name:'Длинное имя приложения '+('тест '.repeat(20)),executable_path:'C:/fixture/not-a-real-app.exe'}]:[]);
api.getAppIcon=async()=>null;
api.listAppProxyRules=()=>read('app-rules',[]);
api.listSubscriptionAppProxyRules=()=>read('sub-rules',[]);
api.getRunThroughNimboContextMenuEnabled=()=>read('context-menu',false);
api.getTunnelLogs=()=>read('logs',params.has('fail')?[]:[{timestamp:'12:30:00',source:'Fixture',level:'info',message:'Длинное сообщение '+('без приватных данных '.repeat(20))}]);
api.listActiveConnections=()=>read('connections',[]);
api.crossSyncStart=()=>read('sync-start',sync);
api.crossSyncCancel=()=>read('sync-cancel',sync);
api.crossSyncStatus=()=>read('sync-status',sync);
api.crossSyncListDevices=()=>read('sync-devices',[]);
useAppStore.setState({preferences:{...defaultAppPreferences,ui_style:style,language:'ru',theme_mode:params.get('theme')==='light'?'light':'dark'},status:null,subscriptions:[],hydrate:async()=>{}});
useCoreStore.setState({loaded:true,data:{preferred_core:'auto',active_profile_id:null,profiles:[]},runtime:null,refresh:async()=>{},error:null});
const pages:Record<string,React.ReactNode>={routing:<Routing/>,modules:<RoutingModules/>,apps:<Applications/>,connections:<Connections/>,logs:<TunnelLogs/>,sync:<CrossPlatformSync/>,mihomo:<MihomoProfiles/>};
createRoot(document.getElementById('root')!).render(<MemoryRouter initialEntries={['/'+mode]}><main className="app-main" style={{margin:0,padding:16,minWidth:0}}>{pages[mode]}</main></MemoryRouter>);
