# API generated by libXray is called from Kotlin and bound to libgojni through
# JNI. Neither its class names nor its members may be renamed or removed.
-keep class libXray.** { *; }

# AmneziaWG native bridge binds to libwg-go.so through JNI entry points.
# The class name and all external members must survive minification.
-keep class com.danila.nimbo.awg.AmneziaWgLibrary { *; }
-keepclassmembers class com.danila.nimbo.awg.AmneziaWgLibrary {
    static *** awgTurnOn(...);
    static *** awgTurnOff(...);
    static *** awgGetSocketV4(...);
    static *** awgGetSocketV6(...);
    static *** awgGetConfig(...);
    static *** awgVersion(...);
}

# WorkManager instantiates workers from their persisted class names after the
# process restarts. Keep those names and their Context/WorkerParameters ctors.
-keep class com.danila.nimbo.network.UpdateWorker { <init>(...); }
-keep class com.danila.nimbo.service.SubscriptionUpdateWorker { <init>(...); }

# Gson persists these models in SharedPreferences and log files. Preserve their
# field names to keep existing user data readable after the first minified build.
-keep class com.danila.nimbo.model.** { *; }
-keep class com.danila.nimbo.ui.screens.SubscriptionProfile { *; }
-keep class com.danila.nimbo.ui.screens.SubscriptionTemplateCache { *; }
-keepattributes Signature,*Annotation*,InnerClasses,EnclosingMethod
-keepclassmembers,allowobfuscation class * {
    @com.google.gson.annotations.SerializedName <fields>;
}

# Firebase/ML Kit discovers ComponentRegistrar implementations from manifest
# metadata and creates them reflectively. The dependency's consumer rule keeps
# their class names, but with current R8 it does not keep the no-arg constructor.
# Without it BarcodeRegistrar is skipped and BarcodeScanning.getClient() gets a
# null scanner factory in minified release builds.
-keep class * implements com.google.firebase.components.ComponentRegistrar {
    public <init>();
}
